name: Release
"on":
  push:
    branches:
      - master
      - next
      - hotfix
jobs:
  pre-release:
    name: dry run pre-release
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/next'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
      - run: npx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  # release:
  #   name: release
  #   if: github.ref == 'refs/heads/master'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         cache: npm
  #         node-version: 16

  #     - run: npx semantic-release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
