name: Release
"on":
  push:
    branches:
      - master
      - next
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16

      - name: Dry Run the release
        if: github.head_ref == 'next' || github.base_ref == 'master'
        run: npx semantic-release --dry-run

      - name: Run the Release
        if: github.head_ref == 'master'
        run: npx semantic-release

        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
