name: Release
"on":
  push:
    branches:
      - master
      - next
jobs:
  logger:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo ${{ github.event }}
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16

      - name: Dry Run the release
        # if: github.ref == 'refs/head/next'
        run: npx semantic-release --dry-run

        # - name: Run the Release
        #   if: github.ref == 'refs/head/master'
        #   run: npx semantic-release

        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
